server:
  port: 8080



spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/webmuasam"
    username: root
    password: 123456
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    web:
      pageable:
        one-indexed-parameters: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: hoalv1237890@gmail.com
    password: aypncppjywqnhgbh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  #upload file
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
jwt:
  signerKey: "S4/BDhmDFzk+cAEFxOJ7kt4kBnMCHKcs8Yco/jboh/IMBsTgj8PlMnq/spmBjh+N"
  valid-duration: 8640000 #in second
  refreshable-duration : 6840000 #in seconds

example:
  base-uri: file:///D:/JAVA/upload/

payment:
  vnpay:
    tmn-code: 02FQMDTI
    secret-key: 0Y1VGU6SIFL36G2UDG6EAR271M79Q6ZP
    init-payment-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    return-url: https://29cb9322100f.ngrok-free.app/order/%s/status
    timeout: 15 # in minutes